name: "Split changes by CODEOWNERS (bucketize + patches)"
description: "Bucketizes local git changes by effective CODEOWNERS and can optionally create one PR per bucket (no third-party PR actions)."
author: "anatoliisf"
branding:
  icon: "shuffle"
  color: "blue"

inputs:
  repo_path:
    description: "Relative path under GITHUB_WORKSPACE to the repo root."
    required: false
    default: "."

  codeowners_path:
    description: "Path to CODEOWNERS. Defaults to CODEOWNERS at repo root."
    required: false
    default: "CODEOWNERS"

  base_ref:
    description: "Optional base ref for changed files discovery. If empty, uses HEAD vs working tree."
    required: false
    default: ""

  include_unowned:
    description: "Include files with no owners in a special bucket"
    required: false
    default: "true"

  unowned_bucket_key:
    description: "Bucket key for unowned files"
    required: false
    default: "__UNOWNED__"

  max_buckets:
    description: "Fail if buckets exceed this number"
    required: false
    default: "30"

  exclude_patterns:
    description: "Newline-separated glob patterns to exclude"
    required: false
    default: ""

  patch_dir:
    description: "Directory to write patches"
    required: false
    default: "bucket-patches"

  bucket_prefix:
    description: "Patch file prefix"
    required: false
    default: "bucket"

  dry_run:
    description: "Compute buckets but don't write patches"
    required: false
    default: "false"

  cleanup_patches:
    description: "If true, delete patch_dir after successful run (useful when create_prs=true)."
    required: false
    default: "false"

  create_prs:
    description: "If true, create/update one PR per bucket by pushing branches and calling GitHub API."
    required: false
    default: "true"

  github_token:
    description: "GitHub token used for API + pushing branches. Defaults to GITHUB_TOKEN."
    required: false
    default: ""

  base_branch:
    description: "Base branch to open PRs against. If empty, uses repo default branch."
    required: false
    default: ""

  branch_prefix:
    description: "Prefix for created branches."
    required: false
    default: "codemods/"

  commit_message:
    description: "Commit message used in bucket PRs."
    required: false
    default: "chore: automated changes"

  pr_title:
    description: "PR title template. Supports {owners} and {bucket_key}."
    required: false
    default: "chore: automated changes ({owners})"

  pr_body:
    description: "PR body template. Supports {owners}, {bucket_key}, {files}."
    required: false
    default: "Automated changes bucketed by CODEOWNERS.\n\nOwners: {owners}\nBucket key: {bucket_key}\n\nFiles:\n{files}\n"

  pr_body_mode:
    description: "PR body mode for PR creation: custom | template | template_with_bucket | none"
    required: false
    default: "template"

  pr_template_path:
    description: "Path to pull request template file (used when pr_body_mode=template*)."
    required: false
    default: ".github/pull_request_template.md"

  draft:
    description: "Create PRs as drafts."
    required: false
    default: "false"

outputs:
  matrix_json:
    description: "JSON for strategy.matrix (one bucket per job)"
  buckets_json:
    description: "Full buckets JSON"
  prs_json:
    description: "If create_prs=true, JSON list of created/updated PRs (url + number + bucket_key)."

runs:
  using: "node20"
  main: "dist/index.js"
